version: "3.9"
services:
  prod:
    build:
      args:
        - HEMLOCK_BOOTSTRAP_OCAML_VERSION
        - HEMLOCK_PLATFORM
        - HEMLOCK_UBUNTU_TAG
      context: .
      dockerfile: .dockerfile
      target: prod
    container_name: branchtaken__hemlock__prod
    cap_add:
      - SYS_PTRACE
    environment:
      - SSH_AUTH_SOCK
    image: branchtaken/hemlock:prod
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - .:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    working_dir: /home/hemlock/Hemlock
  pre-push:
    build:
      args:
        - HEMLOCK_PRE_PUSH_CLONE_PATH
      target: pre-push
    extends: prod
    image: branchtaken/hemlock:pre-push
  dev:
    build:
      args:
        - DOTFILES_HASH
        - DOTFILES_URL
      target: dev
    container_name: branchtaken__hemlock__dev
    extends: prod
    image: branchtaken/hemlock:dev
