name: Test

on: pull_request

jobs:
  run:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v2
      id: cache-opam
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
        restore-keys: |
          ${{ runner.os }}-opam-
    - name: opam
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: '4.11.1'
    - name: deps
      if: steps.cache-opam.outputs.cache-hit != 'true'
      working-directory: ./bootstrap
      run: opam install -t . --deps-only
    - name: build
      working-directory: ./bootstrap
      run: opam exec -- dune build
    - name: test
      working-directory: ./bootstrap
      run: opam exec -- dune runtest
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: check-ocp-indent deps
      run: opam install ocp-indent && git fetch origin master
    - name: check-ocp-indent
      run: python ./.github/scripts/check_ocp_indent.py
