name: Test

on: pull_request

jobs:
  run:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v1
      id: cache-opam
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
    - name: opam
      uses: avsm/setup-ocaml@master
      with:
        ocaml-version: '4.09.0'
    - name: deps
      if: steps.cache-opam.outputs.cache-hit != 'true'
      working-directory: ./bootstrap
      run: opam install -t . --deps-only
    - name: build
      working-directory: ./bootstrap
      run: opam exec -- dune build
    - name: test
      working-directory: ./bootstrap
      run: opam exec -- dune runtest
