name: Test

on: pull_request

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: docker-compose build --platform linux/amd64 prod
    - name: build
      run: docker-compose run prod "dune build"
    - name: test
      run: docker-compose run prod "dune runtest"
    - name: lint
      run: docker-compose run prod "python ./.github/scripts/check_ocp_indent.py"
