name: Test

on: [pull_request, push]

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: docker_compose_build_tested
      run: docker compose build tested
