name: Test

on: [pull_request, status]

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: check-commit-status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HM_PUSH_SHA: ${{ github.event.pull_request.head.sha }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
      run: python3 .github/scripts/check_commit_status.py
